name: Unzip and Create PR

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

jobs:
  unzip-and-pr:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Unzip the tar.gz file
      - name: Extract model.tar.gz
        run: |
          tar -xzf model.tar.gz
          
      # Configure git
      - name: Setup git config
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          
      # Create branch, commit changes, and push
      - name: Create branch and commit
        run: |
          git checkout -b feature/update-model-$(date +%Y%m%d-%H%M%S)
          git add .
          git commit -m "Extract model.tar.gz and update files" || echo "No changes to commit"
          git push origin HEAD
          
      # Create Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: feature/update-model-$(date +%Y%m%d-%H%M%S)
          title: "Update model files from tar.gz"
          body: |
            This PR extracts the contents of model.tar.gz and updates the repository with the new files.
            Automatically generated by GitHub Actions workflow.
          commit-message: "Extract model.tar.gz and update files"