name: Download and Convert MobileBERT to Core ML

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  convert-model:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Use a version compatible with coremltools

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kagglehub coremltools tensorflow

      # Step 4: Download the MobileBERT model from KaggleHub
      - name: Download MobileBERT model
        run: |
          python -c "import kagglehub; path = kagglehub.model_download('google/mobilebert/TensorFlow1/uncased-l-24-h-128-b-512-a-4-f-4-opt/1'); print(f'Model downloaded to: {path}')" > model_path.txt
          cat model_path.txt

      # Step 5: Convert the model to Core ML
      - name: Convert to .mlmodel
        run: |
          MODEL_PATH=$(cat model_path.txt | grep "Model downloaded to:" | cut -d' ' -f3)
          python convert_to_coreml.py "$MODEL_PATH"

      # Step 6: Upload the .mlmodel as an artifact
      - name: Upload Core ML model artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobilebert-mlmodel
          path: mobilebert.mlmodel

      # Optional Step 7: Commit and push the .mlmodel to the repository
      - name: Commit and push model
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add mobilebert.mlmodel
          git commit -m "Add converted MobileBERT .mlmodel"
          git push
        if: success() # Only runs if previous steps succeed