name: Download Model from Kaggle and Create Pull Request

on:
  push:
    branches:
      - main  # Change to the branch you're using if different

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download model from Kaggle
      run: |
        #!/bin/bash
        
        # Hardcoded Kaggle credentials
        export KAGGLE_USERNAME="josephcristini"
        export KAGGLE_KEY="c7709248cdacac4a44ea8beb53595247"

        # Create Downloads directory if it doesn't exist
        mkdir -p ~/Downloads
        
        # Download the model
        curl -L -u $KAGGLE_USERNAME:$KAGGLE_KEY \
          -o ~/Downloads/model.tar.gz \
          https://www.kaggle.com/api/v1/models/josephcristini/backdoor-ai/tensorFlow1/bdg/1/download

    - name: Move model to repository and create new branch
      run: |
        cp ~/Downloads/model.tar.gz ./  # Copy the model to the current directory
        git config --local user.email "you@example.com"  # Set your email
        git config --local user.name "Your Name"  # Set your name
        git checkout -b update-model  # Create a new branch
        git add model.tar.gz  # Add the model file
        git commit -m "Add model.tar.gz from Kaggle"  # Commit the file
        git push --set-upstream origin update-model  # Push the branch to GitHub

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Add model.tar.gz from Kaggle"
        body: "This pull request adds the model downloaded from Kaggle."
        head: update-model
        base: main  # Change to the base branch you want to merge into