name: Download Model from Kaggle

on:
  push:
    branches:
      - main  # Change to the branch you're using if different

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download model from Kaggle
      run: |
        #!/bin/bash
        
        # Hardcoded Kaggle credentials
        export KAGGLE_USERNAME="josephcristini"
        export KAGGLE_KEY="c7709248cdacac4a44ea8beb53595247"

        # Create Downloads directory if it doesn't exist
        mkdir -p ~/Downloads
        
        # Download the model
        curl -L -u $KAGGLE_USERNAME:$KAGGLE_KEY \
          -o ~/Downloads/model.tar.gz \
          https://www.kaggle.com/api/v1/models/josephcristini/backdoor-ai/tensorFlow1/bdg/1/download

    - name: Upload model to repository
      uses: actions/upload-artifact@v2
      with:
        name: model
        path: ~/Downloads/model.tar.gz