name: Convert MobileBERT and Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  convert-and-release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install coremltools tensorflow kaggle

      - name: Download and Convert Model
        run: |
          # Hardcoded Kaggle credentials
          KAGGLE_USERNAME="josephcristini"
          KAGGLE_KEY="ae9de1e12100d4a02f851f52e071f6ea"
          
          # Configure Kaggle CLI
          mkdir -p ~/.kaggle
          echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          
          # Download from Kaggle
          kaggle models instances versions download google/mobilebert/tensorFlow1/uncased-l-24-h-128-b-512-a-4-f-4-opt/1 -p .
          
          # Create extraction directory
          mkdir -p mobilebert_extracted
          
          # Extract tar.gz
          tar -xzf mobilebert.tar.gz -C mobilebert_extracted
          
          # Convert to CoreML
          python3 - <<EOF
          import coremltools as ct
          import tensorflow as tf
          model = tf.keras.models.load_model("mobilebert_extracted/saved_model")
          mlmodel = ct.convert(
              model,
              source="tensorflow",
              inputs=[ct.TensorType(name="input_ids", shape=(1, 128), dtype=tf.int32)],
              respect_trainable=True
          )
          from coremltools.models import optimize
          optimized_model = optimize.quantize_weights(mlmodel, quantization_mode="linear", nbits=8)
          optimized_model.save("MobileBERT.mlmodel")
          EOF

      - name: Create Release and Upload Model
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v1.0.${{ github.run_number }}"
          name: "MobileBERT Release ${{ github.run_number }}"
          body: "Converted MobileBERT for CoreML."
          files: MobileBERT.mlmodel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}