name: Convert Model and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  convert-and-release:
    runs-on: macos-latest # macOS is required for CoreML tools
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Specify your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch transformers onnx-coreml coremltools numpy

      - name: Create Resources directory
        run: mkdir -p ../Resources

      - name: Run conversion script
        run: python convert_model.py # Save your script as convert_model.py

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.date.outputs.date }}
          release_name: Model Conversion ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false

      - name: Upload Full Precision Model
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../Resources/distilbert-squad-384.mlmodel
          asset_name: distilbert-squad-384.mlmodel
          asset_content_type: application/octet-stream

      - name: Upload FP16 Model
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../Resources/distilbert-squad-384_FP16.mlmodel
          asset_name: distilbert-squad-384_FP16.mlmodel
          asset_content_type: application/octet-stream